
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ConditionalNavbar from '../Components/ConditionalNavbar'
// import Navbar from '@/Components/Navbar'
// import { usePathname } from 'next/navigation'
// import { ReactNode, FC } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <body>
      {<ConditionalNavbar />}
        <main className={`${inter.className} flex flex-col min-h-screen w-full items-center justify-center bg-gray-100`}>
        {children}
          </main>


      </body>
    </html>
  )
}
